# Generated by Django 4.0.3 on 2022-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
